config/routes.rb
Rails.application.routes.draw do
  resources :expedients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expedient.rb
class Expedient < ApplicationRecord
    belongs_to :expediente_status
    belongs_to :tipo_solicitud
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expedients_controller.rb
class ExpedientsController < ApplicationController
  before_action :set_expedient, only: %i[ show edit update destroy ]

  # GET /expedients or /expedients.json
  def index
    @expedients = Expedient.all
  end

  # GET /expedients/1 or /expedients/1.json
  def show
  end

  # GET /expedients/new
  def new
    @expedient = Expedient.new
  end

  # GET /expedients/1/edit
  def edit
  end

  # POST /expedients or /expedients.json
  def create
    @expedient = Expedient.new(expedient_params)

    respond_to do |format|
      if @expedient.save
        format.html { redirect_to expedient_url(@expedient), notice: "Expedient was successfully created." }
        format.json { render :show, status: :created, location: @expedient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expedient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expedients/1 or /expedients/1.json
  def update
    respond_to do |format|
      if @expedient.update(expedient_params)
        format.html { redirect_to expedient_url(@expedient), notice: "Expedient was successfully updated." }
        format.json { render :show, status: :ok, location: @expedient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expedient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expedients/1 or /expedients/1.json
  def destroy
    @expedient.destroy

    respond_to do |format|
      format.html { redirect_to expedients_url, notice: "Expedient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expedient
      @expedient = Expedient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expedient_params
      params.require(:expedient).permit(:nombre_solicitante, :apellido_solicitante, :tipo_persona, :edad, :expediente_status_id, :fecha_nacimiento, :tipo_solicitud_id, :cantidad_solicitada, :identificador_unico, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/views/expedients/_expedient.html.erb
<div id="<%= dom_id expedient %>">
  <p>
    <strong>Nombre solicitante:</strong>
    <%= expedient.nombre_solicitante %>
  </p>

  <p>
    <strong>Apellido solicitante:</strong>
    <%= expedient.apellido_solicitante %>
  </p>

  <p>
    <strong>Tipo persona:</strong>
    <%= expedient.tipo_persona %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= expedient.edad %>
  </p>

  <p>
    <strong>Expediente status:</strong>
    <%= expedient.expediente_status_id %>
  </p>

  <p>
    <strong>Fecha nacimiento:</strong>
    <%= expedient.fecha_nacimiento %>
  </p>

  <p>
    <strong>Tipo solicitud:</strong>
    <%= expedient.tipo_solicitud_id %>
  </p>

  <p>
    <strong>Cantidad solicitada:</strong>
    <%= expedient.cantidad_solicitada %>
  </p>

  <p>
    <strong>Identificador unico:</strong>
    <%= expedient.identificador_unico %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= expedient.email %>
  </p>

</div>

app/views/expedients/_form.html.erb
<%= form_with(model: expedient) do |form| %>
  <% if expedient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expedient.errors.count, "error") %> prohibited this expedient from being saved:</h2>

      <ul>
        <% expedient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre_solicitante, style: "display: block" %>
    <%= form.text_field :nombre_solicitante %>
  </div>

  <div>
    <%= form.label :apellido_solicitante, style: "display: block" %>
    <%= form.text_field :apellido_solicitante %>
  </div>

  <div>
    <%= form.label :tipo_persona, style: "display: block" %>
    <%= form.text_field :tipo_persona %>
  </div>

  <div>
    <%= form.label :edad, style: "display: block" %>
    <%= form.text_field :edad %>
  </div>

  <div>
    <%= form.label :fecha_nacimiento, style: "display: block" %>
    <%= form.date_field :fecha_nacimiento %>
  </div>

  <div>
    <%= form.label :cantidad_solicitada, style: "display: block" %>
    <%= form.number_field :cantidad_solicitada %>
  </div>

  <div>
    <%= form.label :identificador_unico, style: "display: block" %>
    <%= form.text_field :identificador_unico %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expedients/edit.html.erb
<h1>Editing expedient</h1>

<%= render "form", expedient: @expedient %>

<br>

<div>
  <%= link_to "Show this expedient", @expedient %> |
  <%= link_to "Back to expedients", expedients_path %>
</div>

app/views/expedients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expedients</h1>

<div id="expedients">
  <% @expedients.each do |expedient| %>
    <%= render expedient %>
    <p>
      <%= link_to "Show this expedient", expedient %>
    </p>
  <% end %>
</div>

<%= link_to "New expedient", new_expedient_path %>

app/views/expedients/new.html.erb
<h1>New expedient</h1>

<%= render "form", expedient: @expedient %>

<br>

<div>
  <%= link_to "Back to expedients", expedients_path %>
</div>

app/views/expedients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expedient %>

<div>
  <%= link_to "Edit this expedient", edit_expedient_path(@expedient) %> |
  <%= link_to "Back to expedients", expedients_path %>

  <%= button_to "Destroy this expedient", @expedient, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaProyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>